### ISSUE TITLE
Might Not Be Needed

### ISSUE THREAD

**Issue by nburuca** [nburuca/ako#1]
https://github.com/nburuca/ako/blob/63ed1c11e012b212a1413d7d37ae5584e41b8b8a/src/main/java/com/ako/data/User.java#L18 Might Not Be Needed. The database is set to auto populate the id, createDate, and lastModifyDate fields.

**Comment by prashant-rathod** [comment]
@Id annotation is to tell Spring JPA that this is a primary key. Each @Entity needs an @Id - which is mapped to primary key in the db. 

I tried removing the annotation but it results in an exception - org.hibernate.AnnotationException: No identifier specified for entity: com.ako.data.User

**Comment by nburuca** [comment]
Sorry what i meant was that i dont think we need the java code to generate the ID. I saw setters for the ID but the database will take care of creating the ID.

**Comment by prashant-rathod** [comment]
You're right! I fixed it. Please take a look.
